### ISSUE TITLE
Not responding on Docker 17.06.2-ce

### ISSUE THREAD

**Issue by bizmate** [sshipway/Portus#16]
I have just created a stack on top of the latest 17.06 docker and it had already some naming problems with the volumes due to forward slashes. I created a PR for this on the catalogue.
https://github.com/rancher/community-catalog/pull/615

But also I get a

ERR_EMPTY_RESPONSE

When calling my registry UX (portus) on port 5443.
I am unfamiliar with portus and I was wondering if you could suggest what I can look for to fix it?

The docker compose i used while PR is reviewed

```
version: '2'
services:
  registry:
    image: registry:2.3.1
    environment:
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_ISSUER: registry.Biz.link
      REGISTRY_AUTH_TOKEN_REALM: https://registry.Biz.link:5443/v2/token
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/registry.crt
      REGISTRY_AUTH_TOKEN_SERVICE: registry.Biz.link:5000
      REGISTRY_HTTP_SECRET: httpsecret
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry.key
      REGISTRY_LOG_LEVEL: warn
      REGISTRY_NOTIFICATIONS_ENDPOINTS: |
        - name: portus
          url: http://portus:3000/v2/webhooks/events
          timeout: 500
          threshold: 5
          backoff: 1
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    stdin_open: true
    volumes:
    - BizRegistry-Certs:/certs
    - BizRegistry-Data:/var/lib/registry
    tty: true
    links:
    - portus:portus
  lb:
    image: rancher/lb-service-haproxy:v0.7.9
    stdin_open: true
    tty: true
    ports:
    - 5000:5000/tcp
    - 5443:5443/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:not_host_label: registry.enabled=false
      io.rancher.scheduler.global: 'true'
  sslproxy:
    image: nginx:1.9.9
    stdin_open: true
    volumes:
    - BizRegistry-Certs:/etc/nginx/certs:ro
    - BizRegistry-Proxy:/etc/nginx/conf.d:ro
    tty: true
    links:
    - portus:portus
    labels:
      io.rancher.scheduler.affinity:container_label_soft: registry.portus.db=1
  db:
    image: mysql:5.7.10
    environment:
      MYSQL_DATABASE: portus
      MYSQL_PASSWORD: '}4?Gxxxxx'
      MYSQL_ROOT_PASSWORD: 0jDIxxxxxx
      MYSQL_USER: portus
    stdin_open: true
    volumes:
    - BizRegistry-Db:/var/lib/mysql
    tty: true
    labels:
      registry.portus.db: '1'
  portus:
    image: sshipway/portus:2.0.5
    environment:
      PORTUS_CHECK_SSL_USAGE_ENABLED: 'true'
      PORTUS_GRAVATAR_ENABLED: 'true'
      PORTUS_KEY_PATH: /certs/registry.key
      PORTUS_LDAP_AUTHENTICATION_BIND_DN: ou=portus,dc=company,dc=com
      PORTUS_LDAP_AUTHENTICATION_ENABLED: 'false'
      PORTUS_LDAP_AUTHENTICATION_PASSWORD: password
      PORTUS_LDAP_BASE: ou=People,dc=company,dc=com
      PORTUS_LDAP_ENABLED: 'false'
      PORTUS_LDAP_GUESS_EMAIL_ATTR: mail
      PORTUS_LDAP_GUESS_EMAIL_ENABLED: 'true'
      PORTUS_LDAP_HOSTNAME: ldap.company.com
      PORTUS_LDAP_METHOD: starttls
      PORTUS_LDAP_PORT: '389'
      PORTUS_LDAP_UID: cn
      PORTUS_MACHINE_FQDN: registry.Biz.link
      PORTUS_PASSWORD: '}4?Gl=bD;S91cERr'
      PORTUS_PORT: '5443'
      PORTUS_PRODUCTION_DATABASE: portus
      PORTUS_PRODUCTION_HOST: db
      PORTUS_PRODUCTION_PASSWORD: '}4?Gxxxxxxx'
      PORTUS_PRODUCTION_USERNAME: portus
      PORTUS_SECRET_KEY_BASE: 0jDISxxxxx
      PORTUS_SMTP_ENABLED: 'false'
      REGISTRY_HOSTNAME: registry.Biz.link
      REGISTRY_NAME: Registry
      REGISTRY_PORT: '5000'
      REGISTRY_SSL_ENABLED: 'true'
    stdin_open: true
    volumes:
    - BizRegistry-Certs:/certs
    - BizRegistry-Proxy:/etc/nginx/conf.d
    tty: true
    links:
    - db:db
    labels:
      registry.portus.app: '1'
      io.rancher.scheduler.affinity:container_label_soft: registry.portus.db=1
      io.rancher.container.pull_image: always

```
